general.live_config_reload = true

[font]
size = 10

[font.bold]
family = "FiraCode Nerd Font"
style = "Bold"

[font.bold_italic]
family = "FiraCode Nerd Font"
style = "Bold Italic"

[font.italic]
family = "FiraCode Nerd Font"
style = "Italic"

[font.normal]
family = "FiraCode Nerd Font"
style = "Regular"

[scrolling]
history = 2000
multiplier = 20

[terminal.shell]
args = ["-l"]
program = "/usr/bin/zsh"

[window]
decorations = "none"
dynamic_padding = false
startup_mode = "Windowed"
title = "Alacritty"

[window.dimensions]
columns = 0
lines = 0

[window.padding]
x = 5
y = 5
